globals = {'LibStub', 'GetBuildInfo', 'UIDROPDOWNMENU_MAXLEVELS', 'UIDROPDOWNMENU_MAXBUTTONS', 'UIDD_REFRESH_OVERREAD_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_PATCH_VERSION', 'UIDROPDOWNMENU_OPEN_MENU', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'COMMUNITY_UIDD_REFRESH_PATCH_VERSION', 'RAID_CLASS_COLORS', 'LOCALIZED_CLASS_NAMES_MALE', 'CLASS_ICON_TCOORDS', 'ALL', 'ARENA_2V2', 'ARENA_3V3', 'BATTLEGROUND_10V10', 'MAX_CLASSES', 'BATTLEGROUND', 'AUCTION_DURATION', 'DAMAGE', 'WIN', 'SHOW_COMBAT_HEALING', 'HONOR', 'RATING', 'TEAM', 'ENEMY', 'ARENA', 'hooksecurefunc', 'issecurevariable', 'FriendsFrame', 'FriendsTabHeader', 'SLASH_REFLEX1'}
ignore = {'self', '532'}
max_line_length = false
self = false
