sudo: false
language: c

addons:
  apt:
    packages:
    - pandoc

install:
  - echo -e "[alias]\nclone = clone --insecure" > ~/.hgrc

script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
