if GetLocale() ~= "deDE" then return end

--Translation by Gixx
REFlexLocale:CreateLocaleTable({
	["A Rating"] = "A Wertung",
	Affliction = "Gebrechen",
	Arcane = "Arkan",
	["Arena support"] = "Arenaunterst\195\188tzung", -- Needs review
	Arms = "Waffen",
	Assassination = "Meucheln",
	Balance = "Gleichgewicht",
	["Bar 1"] = "Bar 1",
	["Bar 2"] = "Bar 2",
	["Beast Mastery"] = "Tierherrschaft",
	Blood = "Blut",
	["Both Specs"] = "Beide Spez",
	Combat = "Kampf",
	Date = "Datum",
	Demonology = "D\195\164monologie",
	Destruction = "Zerst\195\182rung",
	Discipline = "Disziplin",
	["Easiest compositions"] = "Einfachste Zusammenstellung",
	Elemental = "Elementarkampf",
	Enhancement = "Verst\195\164rkung",
	Feral = "Wilder Kampf",
	Fire = "Feuer",
	Frost = "Frost",
	Fury = "Furor",
	["H Rating"] = "H Wertung",
	["Hardest compositions"] = "Schwerste Zusammenstellung",
	["Hold SHIFT key when browsing arena matches to see extended tooltips."] = "Halte SHIFT w\195\164hrend des Anschauens von Arenapartien f\195\188r einen erweiterten Tooltip.", -- Needs review
	Holy = "Heilig",
	["Honor Kills"] = "Ehrenhafte Todesst\195\182\195\159e",
	["Issue command second time to confirm database wipe"] = "Issue command second time to confirm database wipe", -- Requires localization
	["K/D Ratio"] = "K/D Rate",
	["LDB - Show Honorable Kills"] = "LDB - Zeige ehrenhafte Todesst\195\182\195\159e", -- Needs review
	["LDB - Show remaining CP limit"] = "LDB - Zeige verbleibendes CP Limit", -- Needs review
	Left = "Links",
	Map = "Karte",
	Marksmanship = "Treffsicherheit",
	["MiniBar modules"] = "MiniBar Module",
	["MiniBar scale"] = "MiniBar Skalierung",
	["Most common compositions"] = "Gebr\195\164uchlichste Zusammenstellung",
	["New version released!"] = "Neue Version ver\195\182ffentlicht!", -- Needs review
	Old = "Alt",
	Place = "Platzierung",
	Protection = "Schutz",
	RECORD = "REKORD",
	Rated = "Gewertet",
	["Rated BGs"] = "Gew Schlachtfelder",
	["Rated battlegrounds support"] = "Unterst\195\188tzung Gew Schlachtfelder", -- Needs review
	["Reloaded MiniBar settings"] = "Neu geladene MiniBar Einstellungen gesetzt", -- Needs review
	Restoration = "Wiederherstellung",
	Retribution = "Vergeltung",
	Right = "Rechts",
	Shadow = "Schattenmagie",
	["Show LDB MiniBar (Battlegrounds only)"] = "Zeige LDB MiniBar (nur in Schlachtfeldern)", -- Needs review
	["Show MiniBar (Battlegrounds only)"] = "Zeige MiniBar (nur in Schlachtfeldern)",
	["Show detected builds"] = "Zeige entdeckte Spezialisierungen",
	["Show main window"] = "Zeige Hauptfenster",
	["Show minimap button"] = "Zeige MiniMap Knopf",
	["Spec 1"] = "Spez 1",
	["Spec 2"] = "Spez 2",
	Subtlety = "T\195\164uschung",
	Survival = "\195\156berleben",
	Top = "Bestes",
	Total = "Gesamt",
	Unholy = "Unheilig",
	["Unrated BGs"] = "Ungew Schlachtfelder",
	["Unrated battlegrounds support"] = "Unterst\195\188tzung Ungew Schlachtfelder", -- Needs review
});
