if GetLocale() ~= "esES" then return end

--Translation by karrash76
REFlexLocale:CreateLocaleTable({
	["Allow sending daily statistics to other guild members"] = "Permitir enviar diariamente las estad\195\173sticas a otros miembros de la hermandad", -- Needs review
	["A Rating"] = "Clasificaci\195\179n A", -- Needs review
	["Arena support"] = "Soporte de Arena", -- Needs review
	["Are you sure you want to delete this entry?"] = "\194\191Estas seguro que quieres borrar esta entrada?", -- Needs review
	Attendance = "Asistencia", -- Needs review
	["Bar 1"] = "Barra 1", -- Needs review
	["Bar 2"] = "Barra 2", -- Needs review
	["Both Specs"] = "Ambas Especializaciones", -- Needs review
	Date = "Fecha", -- Needs review
	["Easiest compositions"] = "Composiciones M\195\161s F\195\161ciles", -- Needs review
	["Guild query"] = "Consulta de hermandad", -- Needs review
	["Hardest compositions"] = "Composiciones M\195\161s Dif\195\173ciles", -- Needs review
	["Hold SHIFT key when browsing arena matches to see extended tooltips."] = "Presione MAYUS mientras navega por los encuentros de arena para ver descripciones ampliadas", -- Needs review
	["Hold SHIFT key when browsing rated battleground to see extended tooltips."] = "Manten apretado MAYUS cuando navegues por los campos de batalla puntuados para ver informaci\195\179n ampliada", -- Needs review
	["Honor Kills"] = "Muertes con Honor", -- Needs review
	["H Rating"] = "Clasificaci\195\179n H", -- Needs review
	["Issue command second time to confirm database wipe"] = "Confirmar orden por segunda vez para confirmar el borrado total de la base de datos", -- Needs review
	["K/D Ratio"] = "Proporci\195\179n MA/MP", -- Needs review
	["Last active"] = "\195\154ltimo activo", -- Needs review
	Left = "Izquierda", -- Needs review
	Map = "Mapa", -- Needs review
	["MiniBar modules"] = "M\195\179dulos de MiniBarras", -- Needs review
	["MiniBar scale"] = "Escala de MiniBarra", -- Needs review
	["Most common compositions"] = "Composiciones M\195\161s Comunes", -- Needs review
	["New version released!"] = "\194\161Nueva versi\195\179n disponible!", -- Needs review
	Old = "Antiguo", -- Needs review
	Place = "Lugar", -- Needs review
	["Player disabled data sharing."] = "El jugador ha deshabilitado la compartici\195\179n de datos", -- Needs review
	["Please wait before sending another query."] = "Por favor, espera antes de mandar otra consulta", -- Needs review
	Rated = "Puntuado", -- Needs review
	["Rated battlegrounds support"] = "Soporte de Campos de Batalla Puntuados", -- Needs review
	["Rated BGs"] = "CdB Puntuados", -- Needs review
	RECORD = "R\195\137CORD", -- Needs review
	["Reloaded MiniBar settings"] = "Recargar configuraci\195\179n de MiniBarra", -- Needs review
	Right = "Derecha", -- Needs review
	["Show amount of CPs to cap"] = "Mostrar cantidad de CPs para llegar al limite", -- Needs review
	["Show Arena totals"] = "Mostrar totales de Arenas", -- Needs review
	["Show Battleground totals"] = "Mostrar totales de Campos de Batalla", -- Needs review
	["Show detected builds"] = "Mostrar Estructuras Detectadas", -- Needs review
	["Show Honorable Kills"] = "Mostrar Muertes con Honor", -- Needs review
	["Show LDB MiniBar (Battlegrounds only)"] = "Mostrar MiniBarra LDB (Solo en Campos de Batalla)", -- Needs review
	["Show main window"] = "Mostrar ventana principal", -- Needs review
	["Show MiniBar (Battlegrounds only)"] = "Mostrar MiniBarra (Campos de Batalla solamente)", -- Needs review
	["Show minimap button"] = "Mostrar bot\195\179n minimapa", -- Needs review
	["Show place instead difference of score"] = "Mostrar lugar en vez de diferencia de puntuaci\195\179n", -- Needs review
	["Show queues"] = "Mostrar colas", -- Needs review
	["Spec 1"] = "Especializaci\195\179n 1", -- Needs review
	["Spec 2"] = "Especializaci\195\179n 2", -- Needs review
	Top = "Superior", -- Needs review
	Total = "Total", -- Needs review
	["Unrated battlegrounds support"] = "Soporte Campos de Batalla No Puntuados", -- Needs review
	["Unrated BGs"] = "CdB No Puntuados", -- Needs review
	["Use only records from current season to calculate statistics"] = "Usar solo registros de la actual temporada para calcular las estad\195\173sticas", -- Needs review
});
